services:

  # ── Auth Postgres (used only by auth backend) ──
  db:
    image: postgres:16-alpine
    container_name: postgres_server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TimeIQ
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  auth_backend:
    build: E:\Time_IQ_Auth_service
    container_name: auth_Backend
    env_file:
      - E:\Time_IQ_Auth_service\.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always
  
  core_backend:
    build: .\
    container_name: TimeIQ_core_backend
    env_file:
      - .\.env
    environment:
      - POSTGRES_DB_URL=postgresql+asyncpg://postgres:pugazh%402005@host.docker.internal:5432/TimeIQ
      - SYNC_POSTGRES_DB_URL=postgresql+psycopg2://postgres:pugazh%402005@host.docker.internal:5432/TimeIQ
    ports:
      - "8001:8001"
    restart: always

  frontend:
    build: E:\TimeIQ-Front-end
    container_name: TimeIq-frontend
    depends_on:
      - auth_backend
      - core_backend
    ports:
      - "3000:80"
    restart: always

  redis:
    image: redis:7-alpine
    container_name: timeiq-redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  celery-watcher:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: timeiq-celery-watcher-final
    command: celery -A src.workers.celery_app.celery_app worker -Q watcher -n watcher@%h -l info
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_DB_URL=postgresql+asyncpg://postgres:pugazh%402005@host.docker.internal:5432/TimeIQ
      - SYNC_POSTGRES_DB_URL=postgresql+psycopg2://postgres:pugazh%402005@host.docker.internal:5432/TimeIQ
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: unless-stopped

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: timeiq-celery-beat-final
    command: celery -A src.workers.celery_app.celery_app beat -l info
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_DB_URL=postgresql+asyncpg://postgres:pugazh%402005@host.docker.internal:5432/TimeIQ
      - SYNC_POSTGRES_DB_URL=postgresql+psycopg2://postgres:pugazh%402005@host.docker.internal:5432/TimeIQ
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: unless-stopped

  celery-processor:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: timeiq-celery-processor-final
    command: celery -A src.workers.celery_app.celery_app worker -Q processor -n processor@%h -l info -c 4
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_DB_URL=postgresql+asyncpg://postgres:pugazh%402005@host.docker.internal:5432/TimeIQ
      - SYNC_POSTGRES_DB_URL=postgresql+psycopg2://postgres:pugazh%402005@host.docker.internal:5432/TimeIQ
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data: