"""Add conflict fields to timesheet

Revision ID: 28960134e1b7
Revises:
Create Date: 2026-04-03 15:04:29.593482

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "28960134e1b7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "email_messages",
        "processed_status",
        existing_type=sa.VARCHAR(length=12),
        nullable=False,
    )
    op.alter_column("holidays", "client_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("holidays", "holiday_date", existing_type=sa.DATE(), nullable=False)
    op.alter_column("holidays", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("holidays", "type", existing_type=sa.VARCHAR(), nullable=False)
    op.create_index(
        op.f("ix_holidays_holiday_date"), "holidays", ["holiday_date"], unique=False
    )
    op.add_column("timesheets", sa.Column("has_conflict", sa.Boolean(), nullable=True))
    op.add_column(
        "timesheets", sa.Column("conflict_reason", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "timesheets",
        sa.Column(
            "detected_employee_names",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("timesheets", "detected_employee_names")
    op.drop_column("timesheets", "conflict_reason")
    op.drop_column("timesheets", "has_conflict")
    op.drop_index(op.f("ix_holidays_holiday_date"), table_name="holidays")
    op.alter_column("holidays", "type", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("holidays", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("holidays", "holiday_date", existing_type=sa.DATE(), nullable=True)
    op.alter_column("holidays", "client_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column(
        "email_messages",
        "processed_status",
        existing_type=sa.VARCHAR(length=12),
        nullable=True,
    )
    # ### end Alembic commands ###
