"""initial core tables

Revision ID: 839cbded797e
Revises: 
Create Date: 2026-03-17 10:54:00.384501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '839cbded797e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('audit_log_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('audit_log_id')
    )
    op.create_table('clients',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('client_name', sa.String(length=150), nullable=True),
    sa.Column('client_code', sa.String(length=50), nullable=True),
    sa.Column('client_email', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('client_code')
    )
    op.create_table('employees',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('emp_email', sa.String(length=150), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('paycodes',
    sa.Column('paycode_id', sa.UUID(), nullable=False),
    sa.Column('paycode', sa.String(length=50), nullable=True),
    sa.Column('paycode_name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('paycode_id'),
    sa.UniqueConstraint('paycode')
    )
    op.create_table('assignments',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('regular_rate', sa.Numeric(), nullable=True),
    sa.Column('overtime_rate', sa.Numeric(), nullable=True),
    sa.Column('double_time_rate', sa.Numeric(), nullable=True),
    sa.Column('paycode_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['paycode_id'], ['paycodes.paycode_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('client_rules',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=True),
    sa.Column('rule_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('email_threads',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('thread_id'),
    sa.UniqueConstraint('gmail_thread_id')
    )
    op.create_table('email_whitelist',
    sa.Column('email_whitelist_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('allowed_email', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('email_whitelist_id')
    )
    op.create_table('payroll_exports',
    sa.Column('export_id', sa.UUID(), nullable=False),
    sa.Column('week_ending', sa.Date(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('exported_by', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('export_id')
    )
    op.create_table('email_messages',
    sa.Column('email_message_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('sender_email', sa.String(length=150), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_reply', sa.Boolean(), nullable=True),
    sa.Column('processed_status', sa.Enum('INGESTED', 'CLASSIFYING', 'CLASSIFIED', 'IGNORED', 'EXTRACTING', 'EXTRACTED', 'COMPLETED', 'FAILED', 'NEEDS_REVIEW', name='processed_status_enum', native_enum=False), nullable=True),
    sa.Column('classification', sa.Enum('TIMESHEET', 'OTHER', name='email_classification_enum', native_enum=False), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['email_threads.thread_id'], ),
    sa.PrimaryKeyConstraint('email_message_id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_table('payroll_ready_entries',
    sa.Column('payroll_entry_id', sa.UUID(), nullable=False),
    sa.Column('export_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('week_ending', sa.Date(), nullable=True),
    sa.Column('regular_hours', sa.Numeric(), nullable=True),
    sa.Column('overtime_hours', sa.Numeric(), nullable=True),
    sa.Column('double_time_hours', sa.Numeric(), nullable=True),
    sa.Column('regular_rate', sa.Numeric(), nullable=True),
    sa.Column('overtime_rate', sa.Numeric(), nullable=True),
    sa.Column('double_time_rate', sa.Numeric(), nullable=True),
    sa.Column('total_pay', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['export_id'], ['payroll_exports.export_id'], ),
    sa.PrimaryKeyConstraint('payroll_entry_id')
    )
    op.create_table('email_attachments',
    sa.Column('attachment_id', sa.UUID(), nullable=False),
    sa.Column('email_message_id', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processing_status', sa.Enum('INGESTED', 'CLASSIFYING', 'CLASSIFIED', 'IGNORED', 'EXTRACTING', 'EXTRACTED', 'COMPLETED', 'FAILED', 'NEEDS_REVIEW', name='processed_status_enum', native_enum=False), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_messages.email_message_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('timesheets',
    sa.Column('timesheet_id', sa.UUID(), nullable=False),
    sa.Column('email_message_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('week_ending', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('extraction_status', sa.String(length=50), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(), nullable=True),
    sa.Column('raw_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_messages.email_message_id'], ),
    sa.PrimaryKeyConstraint('timesheet_id')
    )
    op.create_table('approvals',
    sa.Column('approval_id', sa.UUID(), nullable=False),
    sa.Column('timesheet_id', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['timesheet_id'], ['timesheets.timesheet_id'], ),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_table('manual_reviews',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('timesheet_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['timesheet_id'], ['timesheets.timesheet_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('rule_violations',
    sa.Column('violation_id', sa.UUID(), nullable=False),
    sa.Column('timesheet_id', sa.UUID(), nullable=True),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['client_rules.rule_id'], ),
    sa.ForeignKeyConstraint(['timesheet_id'], ['timesheets.timesheet_id'], ),
    sa.PrimaryKeyConstraint('violation_id')
    )
    op.create_table('time_entries_raw',
    sa.Column('timeentry_id', sa.UUID(), nullable=False),
    sa.Column('timesheet_id', sa.UUID(), nullable=True),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('regular_hours', sa.Numeric(), nullable=True),
    sa.Column('overtime_hours', sa.Numeric(), nullable=True),
    sa.Column('double_time_hours', sa.Numeric(), nullable=True),
    sa.Column('paycode_id', sa.UUID(), nullable=True),
    sa.Column('matching_status', sa.String(length=50), nullable=False),
    sa.Column('employee_unmatched_reason', sa.String(length=500), nullable=True),
    sa.Column('client_unmatched_reason', sa.String(length=500), nullable=True),
    sa.Column('match_confidence', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['paycode_id'], ['paycodes.paycode_id'], ),
    sa.ForeignKeyConstraint(['timesheet_id'], ['timesheets.timesheet_id'], ),
    sa.PrimaryKeyConstraint('timeentry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_entries_raw')
    op.drop_table('rule_violations')
    op.drop_table('manual_reviews')
    op.drop_table('approvals')
    op.drop_table('timesheets')
    op.drop_table('email_attachments')
    op.drop_table('payroll_ready_entries')
    op.drop_table('email_messages')
    op.drop_table('payroll_exports')
    op.drop_table('email_whitelist')
    op.drop_table('email_threads')
    op.drop_table('client_rules')
    op.drop_table('assignments')
    op.drop_table('paycodes')
    op.drop_table('employees')
    op.drop_table('clients')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
